CREATE TABLE IRAKASLEAK (
    IZENA VARCHAR2(10) UNIQUE,
    ABIZENA1 VARCHAR2(15),
    ABIZENA2 VARCHAR2(15),
    IFZ VARCHAR2(9),
    HELBIDEA VARCHAR2(30),
    TITULAZIOA VARCHAR2(30),
    SOLDATA NUMBER(6,2) NOT NULL,
    CONSTRAINT PK_IRAKASLEAK PRIMARY KEY(IFZ)
);

CREATE TABLE IKASTAROAK (
    IZENA VARCHAR2(10) UNIQUE,
    KODEA NUMBER(5),
    IFZ_IRAKASLE VARCHAR2(9),
    IKASLE_MAXIMOA NUMBER(3),
    HASIERA_DATA DATE,
    AMAIERA_DATA DATE,
    ORDU_KOPURUA NUMBER(3) NOT NULL,
    CONSTRAINT PK_IKASTAROAK PRIMARY KEY(KODEA),
    CONSTRAINT FK_IRA_IFZ FOREIGN KEY(IFZ_IRAKASLE) REFERENCES IRAKASLEAK (IFZ),
    CONSTRAINT CK_IKA_DAT CHECK(AMAIERA_DATA > HASIERA_DATA)
);

CREATE TABLE IKASLEAK (
    IZENA VARCHAR2(10),
    ABIZENA1 VARCHAR2(15),
    ABIZENA2 VARCHAR2(15),
    IFZ VARCHAR2(9),
    HELBIDEA VARCHAR2(30),
    SEXUA VARCHAR2(1),
    JAIOTZE_DATA DATE,
    IKASTARO_KODEA NUMBER(5),
    CONSTRAINT PK_IKASLEAK PRIMARY KEY(IFZ),
    CONSTRAINT FK_IKA_KOD FOREIGN KEY (IKASTARO_KODEA) REFERENCES IKASTAROAK (KODEA),
    CONSTRAINT CK_IKA_SEX CHECK (SEXUA IN ('E','G','B'))
);

-- 1. Sortu adina izeneko eremu berri bat IKASLEAK taulan.
ALTER TABLE IKASLEAK ADD ADINA NUMBER(3);
-- 2. Aldatu aurretik sortu duzun eremua, ikaslearen adina 14 eta 65 urte artekoa izan dadin.
ALTER TABLE IKASLEAK ADD CONSTRAINT CK_IKA_ADI CHECK(ADINA BETWEEN 14 AND 65);
-- 3. IKASTAROAK taulako ordu-kopurua eremuan aldaketak egin, 30, 40 edo 60 orduko ikastaroak bakarrik egon ahal izateko.
ALTER TABLE IKASTAROAK ADD CONSTRAINT CK_IKA_ORD CHECK (ORDU_KOPURUA IN (30, 40, 60));
-- 4. Ezin dugu ikastaro bat gehitu ikasle kopuru maximoa 15 baino txikiagoa bada.
ALTER TABLE IKASTAROAK ADD CONSTRAINT CK_IKA_MAX CHECK(IKASLE_MAXIMOA >=15);
-- 5. Sexua eremua har ditzakeen balioak kontrolatzen dituen murrizketa ezabatu.
ALTER TABLE IKASLEAK DROP CONSTRAINT CK_IKA_SEX;
-- 6. IRAKASLEAK taualatik helbidearen zutabea ezabatu.
ALTER TABLE IRAKASLEAK DROP COLUMN HELBIDEA;
-- 7. IRAKASLEAK taulako gako nagusia aldatu, gako nagusi berria izen-abizenak izango dira.
ALTER TABLE IRAKASLEAK DROP CONSTRAINT PK_IRAKASLEAK CASCADE;
ALTER TABLE IRAKASLEAK ADD CONSTRAINT PK_IRAKASLEAK PRIMARY KEY(IZENA, ABIZENA1, ABIZENA2);
-- 8. IRAKASLEAK taularen izena aldatu. Taularen izen berria TUTOREAK izango da.
RENAME IRAKASLEAK TO TUTOREAK;
-- 9. IKASLEAK taula ezabatu.
DROP TABLE IKASLEAK;











