--ORDENA
--1. AKTIBITATEAK ETA BANKUAK
--2. ERABILTZAILEAK
--3. AKTIBITATEAK_ERABILTZAILEAK ETA ORDAINKETAK
CREATE TABLE AKTIBITATEAK(
    AKTIBITATE_KODEA VARCHAR2(7),
    DESKRIBAPENA VARCHAR2(50) NOT NULL,
    KUOTA NUMBER(7),
    CONSTRAINT PK_AKTIBITATEAK PRIMARY KEY(AKTIBITATE_KODEA)
);

CREATE TABLE BANKUAK(
    ENT_SUK NUMBER(8),
    IZENA VARCHAR2(50),
    HELBIDEA VARCHAR2(50),
    UDALERRIA VARCHAR2(30),
    TELEFONOA VARCHAR2(30),
    CONSTRAINT PK_BANKUAK PRIMARY KEY(ENT_SUK)
);

CREATE TABLE ERABILTZAILEAK(
    BAZKIDE_ZENBAKIA VARCHAR2(7),
    NAN VARCHAR2(9) NOT NULL,
    IZENA VARCHAR2(20),
    ABIZENAK VARCHAR2(30),
    ARGAZKIA LONG RAW,
    HELBIDEA VARCHAR2(40),
    UDALERRIA VARCHAR2(50),
    PK VARCHAR2(5),
    JAIOTZE_DATA DATE,
    TELEFONOA VARCHAR2(20),
    ALTA_DATA DATE,
    BAJA_DATA DATE,
    BAZKIDE_KUOTA NUMBER(7),
    FAMILIA_KUOTA NUMBER(7),
    BANKU_ORDAINKETA CHAR NOT NULL, 
    BANKU_KODEA NUMBER(8),
    KONTUA NUMBER(10),
    KONTROL_DIGITOA NUMBER(2),
    OHARRAK VARCHAR2(500),
    CONSTRAINT PK_ERABILTZAILEAK PRIMARY KEY(BAZKIDE_ZENBAKIA),
    CONSTRAINT FK_BAN_ENTSUK FOREIGN KEY(BANKU_KODEA) REFERENCES BANKUAK(ENT_SUK),
    CONSTRAINT UQ_ERA_NAN UNIQUE(NAN),
    CONSTRAINT CK_ERA_DATA CHECK (BAJA_DATA>ALTA_DATA),
    CONSTRAINT CK_ERA_KUOTA CHECK (FAMILIA_KUOTA>BAZKIDE_KUOTA),
    CONSTRAINT CK_ERA_ORDAINKETA CHECK (BANKU_ORDAINKETA IN ('B','Z'))
	-- Adin nagusiak diren erabiltzaileak baino ez dira onartuko
	-- Baldintza hau ezin da bete, CHECK constraint-ean ezin da SYSDATE
	-- erabili, trigger batekin egin beharko litzateke
);

CREATE TABLE AKTIBITATEAK_ERABILTZAILEAK(
    AKTIBITATE_KODEA VARCHAR2(7) NOT NULL,
    ERABILTZAILE_KODEA VARCHAR2(7) NOT NULL,
    ALTA_DATA DATE,
    BAJA_DATA DATE, 
    CONSTRAINT PK_AKTIBITATEAK_ERABILTZAILEAK PRIMARY KEY (AKTIBITATE_KODEA, ERABILTZAILE_KODEA),
    CONSTRAINT FK_ERA_KODEA FOREIGN KEY (ERABILTZAILE_KODEA) REFERENCES ERABILTZAILEAK(BAZKIDE_ZENBAKIA),
    CONSTRAINT FK_AKT_KODEA FOREIGN KEY (AKTIBITATE_KODEA) REFERENCES AKTIBITATEAK(AKTIBITATE_KODEA),
    CONSTRAINT CK_AKTERA_DATA CHECK (BAJA_DATA>ALTA_DATA)
);

CREATE TABLE ORDAINKETAK(
    ERABILTZAILE_KODEA VARCHAR2(7) NOT NULL,
    HILABETE_ZENBAKIA NUMBER(2) NOT NULL, 
    KUOTA NUMBER(7) DEFAULT 150, 
    OHARRAK VARCHAR2(500),
    CONSTRAINT PK_ORDAINKETAK PRIMARY KEY(ERABILTZAILE_KODEA,HILABETE_ZENBAKIA),
    CONSTRAINT FK_ORD_ERA_KODEA FOREIGN KEY(ERABILTZAILE_KODEA) REFERENCES ERABILTZAILEAK(BAZKIDE_ZENBAKIA),
    CONSTRAINT CK_ORD_HILABETEA CHECK(HILABETE_ZENBAKIA BETWEEN 1 AND 12)
);



