--CREATE USER AZTERKETA IDENTIFIED BY AZTERKETA;
--GRANT ALL PRIVILEGES TO AZTERKETA;

CREATE TABLE ITALIARPELIKULA (
    ID NUMBER(5),
    IZENBURU VARCHAR2(255) NOT NULL,
    URTEA VARCHAR2(4),
    ID_JATORRIZKO_HIZKUNTZA NUMBER(2),
    ALOKAIRU_IRAUPENA NUMBER(1) DEFAULT 3,
    ALOKAIRU_TARIFA NUMBER(4,2) DEFAULT 4.99,
    IRAUPENA NUMBER(3) NOT NULL,
    SAILKAPENA VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_ID PRIMARY KEY (ID),
    CONSTRAINT FK_ID_JATORRIZKO_HIZKUNTZA FOREIGN KEY (ID_JATORRIZKO_HIZKUNTZA)
    REFERENCES HIZKUNTZA(ID),
    CONSTRAINT CHK_SAILKAPENA CHECK (SAILKAPENA IN ('NC-17','R','PG','G'))
);

CREATE TABLE  DENDA (
    ID NUMBER(1),
    IFZ VARCHAR2(9),
    IZENA VARCHAR2(50) NOT NULL,
    HERRIA VARCHAR2(50),
    CONSTRAINT PK_ID PRIMARY KEY(ID)
);

INSERT INTO ITALIARPELIKULA SELECT ID, IZENBURUA, URTEA, ID_JATORRIZKO_HIZKUNTZA, ALOKAIRU_IRAUPENA, ALOKAIRU_TARIFA, IRAUPENA, SAILKAPENA FROM PELIKULA;

