SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE PROCEDURE ProduktuenPrezioaKudeatu (KATEGORIA VARCHAR2, ALDAKETA PRODUKTU.SALNEURRIA%TYPE, ZEIN NUMBER) AS
    E_ALDAKETA EXCEPTION;
BEGIN
        CASE
            WHEN ZEIN = 1 THEN UPDATE PRODUKTU SET SALNEURRIA = SALNEURRIA + (SALNEURRIA * (ALDAKETA/100)) WHERE ID_KATEGORIA = (SELECT ID FROM KATEGORIA WHERE IZENA = KATEGORIA);
            WHEN ZEIN = 0 THEN UPDATE PRODUKTU SET SALNEURRIA = SALNEURRIA + ALDAKETA WHERE ID_KATEGORIA = (SELECT ID FROM KATEGORIA WHERE IZENA = KATEGORIA);
            ELSE RAISE E_ALDAKETA;
        END CASE;
        COMMIT;
EXCEPTION
    WHEN E_ALDAKETA THEN DBMS_OUTPUT.PUT_LINE('Ez duzu ondo aukeratu');
END;
    
EXECUTE ProduktuenPrezioaKudeatu ('CPU',10,1);
