--CREATE USER AZTERKETA IDENTIFIED BY AZTERKETA;
--GRANT ALL PRIVILEGES TO AZTERKETA;

CREATE TABLE ITALIARPELIKULA (
    ID NUMBER(5),
    IZENBURU VARCHAR2(255) NOT NULL,
    URTEA VARCHAR2(4),
    ID_JATORRIZKO_HIZKUNTZA NUMBER(2),
    ALOKAIRU_IRAUPENA NUMBER(1) DEFAULT 3,
    ALOKAIRU_TARIFA NUMBER(4,2) DEFAULT 4.99,
    IRAUPENA NUMBER(3) NOT NULL,
    SAILKAPENA VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_ID PRIMARY KEY (ID),
    CONSTRAINT FK_ID_JATORRIZKO_HIZKUNTZA FOREIGN KEY (ID_JATORRIZKO_HIZKUNTZA)
    REFERENCES HIZKUNTZA(ID),
    CONSTRAINT CHK_SAILKAPENA CHECK (SAILKAPENA IN ('NC-17','R','PG','G'))
);

CREATE TABLE  DENDA (
    ID NUMBER(1),
    IFZ VARCHAR2(9) UNIQUE,
    IZENA VARCHAR2(50) NOT NULL,
    HERRIA VARCHAR2(50),
    CONSTRAINT PK_ID_DENDA PRIMARY KEY(ID)
);

INSERT INTO ITALIARPELIKULA SELECT ID, IZENBURUA, URTEA, ID_JATORRIZKO_HIZKUNTZA, ALOKAIRU_IRAUPENA, ALOKAIRU_TARIFA, IRAUPENA, SAILKAPENA FROM PELIKULA;

INSERT INTO DENDA (ID, IFZ, IZENA, HERRIA)
VALUES ('1' ,'23232323Z' , 'RAMONES', 'BERMEO');

INSERT INTO DENDA (ID, IFZ, IZENA, HERRIA)
VALUES ('2', '32323232Z', 'JAMONES', 'BERMEO');

INSERT INTO BEZERO (ID, ID_DENDA, IZENA, SORTZE_DATA)
VALUES ('600','2','San Jorge',SYSDATE);



ALTER TABLE BEZERO
ADD FOREIGN KEY (ID_DENDA) REFERENCES DENDA(ID);

ALTER TABLE PELIKULA
MODIFY BERRITZE_KOSTUA DEFAULT 19.99;

ALTER TABLE ITALIARPELIKULA ADD EKOIZPEN_DATA DATE;

ALTER TABLE ITALIARPELIKULA DROP CONSTRAINT FK_ID_JATORRIZKO_HIZKUNTZA;

ALTER TABLE ITALIARPELIKULA DROP COLUMN ID_JATORRIZKO_HIZKUNTZA;

DROP TABLE ITALIARPELIKULA;



UPDATE BEZERO
SET IZENA = SAN, ABIZENA = JORGE, DENDA = 1
WHERE ID = 200;

UPDATE PELIKULA
SET ALOKAIRU_TARIFA = (ALOKAIRU_TARIFA*0.1);

DELETE FROM INBENTARIO WHERE ID_DENDA = 2 AND ID_INBENTARIO = (SELECT ID_INBENTARIO FROM ALOKAIRU WHERE ID_INBENTARIO NOT IN );

ALTER TABLE ALOKAIRU DROP CONSTRAINT FP_ALOKAIRU_BEZERO;
ALTER TABLE ALOKAIRU ADD CONSTRAINT FP_ALOKAIRU_BEZERO ON DELETE SET NULL;
DELETE FROM BEZERO WHERE IZENA = 'KATIE' AND ABIZENAK = 'ELLIOTT';



CREATE VIEW VPELIKULA AS
SELECT ID, IZENBURUA, IRAUPENA, SAILKAPENA,  
FROM PELIKULA;


