SET SERVEROUTPUT ON;
SET VERIFY ON;

DECLARE
    IDBEZERO NUMBER(2) := &idBezeroa;
    BEZEROA BEZEROAK.BEZEROIZENA%TYPE; --ZURE_IZENA/TAULA/ZUTABEKO_IZENA
BEGIN

SELECT BEZEROIZENA INTO BEZEROA FROM BEZEROAK
WHERE IDBEZERO = BEZEROKODEA;

DBMS_OUTPUT.PUT_LINE(BEZEROA);

END;

/

DECLARE

    IDBEZERO NUMBER(2) := &idBezeroa;
    BEZEROA BEZEROAK.BEZEROIZENA%TYPE;
    KONTAKTUAI BEZEROAK.KONTAKTUIZENA%TYPE;
    KONTAKTUAA BEZEROAK.KONTAKTUABIZENA%TYPE;
    TELEFONOA BEZEROAK.TELEFONOA%TYPE;
    FAX BEZEROAK.FAX%TYPE;
    HELBIDEA1 BEZEROAK.HELBIDELERROA1%TYPE;
    HELBIDEA2 BEZEROAK.HELBIDELERROA2%TYPE;
    HERRIA BEZEROAK.HERRIA%TYPE;
    ESKUALDEA BEZEROAK.ESKUALDEA%TYPE;
    HERRIALDEA BEZEROAK.HERRIALDEA%TYPE;
    POSTAKODEA BEZEROAK.POSTAKODEA%TYPE;
    SALEROSKETAKODEA BEZEROAK.SALEROSKETALANGILEKODEA%TYPE;
    KREDITUMUGA BEZEROAK.KREDITUMUGA%TYPE;
    
    
BEGIN

    SELECT BEZEROIZENA, KONTAKTUIZENA, KONTAKTUABIZENA, TELEFONOA, FAX, HELBIDELERROA1, HELBIDELERROA2, HERRIA, ESKUALDEA, HERRIALDEA, POSTAKODEA, SALEROSKETALANGILEKODEA, KREDITUMUGA 
    INTO BEZEROA, KONTAKTUAI, KONTAKTUAA, TELEFONOA, FAX, HELBIDEA1, HELBIDEA2, HERRIA, ESKUALDEA, HERRIALDEA, POSTAKODEA, SALEROSKETAKODEA, KREDITUMUGA FROM BEZEROAK
    WHERE IDBEZERO = BEZEROKODEA;
    
    DBMS_OUTPUT.PUT_LINE(BEZEROA, KONTAKTUAI, KONTAKTUAA, TELEFONOA, FAX, HELBIDEA1, HELBIDEA2, HERRIA, ESKUALDEA, HERRIALDEA, POSTAKODEA, SALEROSKETAKODEA, KREDITUMUGA);
    

END;